# Generated by Django 3.0.4 on 2020-04-30 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='rejected', max_length=20)),
                ('doc_cmts', models.CharField(blank=True, max_length=150)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap1', to=settings.AUTH_USER_MODEL)),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
