# Generated by Django 3.0.4 on 2020-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200429_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='def_M.jpg', upload_to='profile_pics'),
        ),
    ]
