# Generated by Django 3.0.4 on 2020-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200430_1722'),
        ('accounts', '0006_auto_20200429_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointments',
            field=models.ManyToManyField(related_name='app_doc', to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='patient',
            name='appointments',
            field=models.ManyToManyField(related_name='app_pat', to='appointment.appointment'),
        ),
    ]
