# Generated by Django 3.0.4 on 2020-04-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.CharField(max_length=500)),
                ('pres', models.CharField(max_length=1000)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re1', to=settings.AUTH_USER_MODEL)),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
