# Generated by Django 3.0.4 on 2020-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pres',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='record',
            name='symptoms',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
