# Generated by Django 3.0.4 on 2020-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200430_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
