# Generated by Django 3.0.4 on 2020-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_record_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_file',
            field=models.FileField(blank=True, upload_to='records'),
        ),
    ]
