# Generated by Django 3.0.4 on 2020-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200525_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
