# Generated by Django 3.0.4 on 2020-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_file',
            field=models.FileField(default='white.png', upload_to='records'),
        ),
    ]
